# Site settings
author: Ernsyka Methelus
title: Erny's Blog
header-img: img/home-bg.png
email: ernsykamethelus@yahoo.com
copyright_name: Ernsyka Methelus
description: > # this means to ignore newlines until "baseurl:"
  Slouching and Coding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ernsykamethelus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
